### ISSUE TITLE
ESAM version?

### ISSUE THREAD

**Issue by jheliker** [scunning1987/pois_reference_server#1]
Hi Scott - 

Thanks for the great example server. 

Looking for clarification - in the readme file you say esam_version must be set to 2016, however, this seems to be built around 2013 (OC-SP-ESAM-API-I03-131025).

For example, the Signal Processing Event found at https://github.com/scunning1987/pois_reference_server/blob/main/spe.json includes sig:BinaryData, which in 2016 (OC-SP-ESAM-API-C01-161021) was replaced with the use of scte35:Binary. It seems all of 2016 migrated to using the SCTE-provided schema.

Any thoughts on this? 

 - James

**Comment by scunning1987** [comment]
Thanks for the feedback. you are correct. On my next update I'll modify the version called out in the rules list. Eventually I'll update the SPN to be 2016. 

Cheers,
