### ISSUE TITLE
AcquisitionPointIdentity

### ISSUE THREAD

**Issue by armored-bazaar** [scunning1987/pois_reference_server#2]
How do I set the AcquisitionPointIdentity?  Is that the channel-name?  Thanks!

**Comment by scunning1987** [comment]
Hi, yes the acquisition point id is the channel name. Let me know if you have any issues, thanks.

**Comment by armored-bazaar** [comment]
Thanks.  That works.  I am trying to setup a channel to do the following.  Is replacing delivery_not_restricted flag supported?

{
  "default_behavior": "noop",
  "esam_version": "2016",
  "rules": [
    {
      "type": "replace",
      "condition":{
      "property": "delivery_not_restricted_flag",
      "value": "true",
      "operator": "="
      },
      "replace_params":[
       {"delivery_not_restricted_flag":"false"}
      ]
    }
  ]
}
